"""second-ya


Revision ID: ab6a1336ff7a
Revises: bed83360d993
Create Date: 2018-03-13 10:44:45.944380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6a1336ff7a'
down_revision = 'bed83360d993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('producers', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'producers')
    # ### end Alembic commands ###
